INSERT INTO usuario (usu_codigo,usu_nombre,usu_apellido,usu_estatura,usu_fecha_nacimiento,usu_tipo_usuario) values("12345","Elias","Solis",165,"1993-10-28",1)
INSERT INTO usuario (usu_codigo,usu_nombre,usu_apellido,usu_estatura,usu_fecha_nacimiento,usu_tipo_usuario) values("5414","Laura","Flores",158,"1995-01-08",0)
INSERT INTO usuario (usu_codigo,usu_nombre,usu_apellido,usu_estatura,usu_fecha_nacimiento,usu_tipo_usuario) values("123123","Mauro","Rendon",174,"2000-05-09",1)
INSERT INTO usuario (usu_codigo,usu_nombre,usu_apellido,usu_estatura,usu_fecha_nacimiento,usu_tipo_usuario) values("456456","Marcos","Chambi",166,"2002-12-15",0)
INSERT INTO usuario (usu_codigo,usu_nombre,usu_apellido,usu_estatura,usu_fecha_nacimiento,usu_tipo_usuario) values("789789","Javier","Burgos",180,"1992-06-01",0)

INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Pollo")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Carne")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Pescado")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Arroz")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Fideo integral")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Tomate")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Lechuga")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Zanahoria")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Cebolla")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Huevo")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Harina integral")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Semillas varias")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Avena")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Nueces")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Granola")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Aceite")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Limón")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Morrón")

INSERT INTO recetas (rec_estado,rec_categoria,rec_imagen,rec_nombre,rec_preparacion) values(1,"Carne","/images/personas1.jpg","Bistec encebollado","*Cortar cebollas en juliana. - *Calentar aceite de oliva en sartén y freír la cebolla. - *Luego de la cebolla, cocinar el bistec y sasonar a gusto.")
INSERT INTO recetas (rec_estado,rec_categoria,rec_imagen,rec_nombre,rec_preparacion) values(1,"Carne","/images/personas2.jpg","Ternera con verduras","*Cortar ternera, zanahoria y cebolla en tiras largas. - *Preparar un wok con una pizca de aceite a fuego lento. - *Cocinar hasta que la cebolla adquiera una tonalidad translúcida.")
INSERT INTO recetas (rec_estado,rec_categoria,rec_imagen,rec_nombre,rec_preparacion) values(1,"Ensalada","/images/personas3.jpeg","Ensalada mixta con arroz","*Cortar tomate y zanahoria en cubos, agregar unas hojas de lechuga. - *Hervir una taza de arroz. - *En un plato, agregar una capa de arroz y otra de verduras. - *Agregar mix de semillas.")
INSERT INTO recetas (rec_estado,rec_categoria,rec_imagen,rec_nombre,rec_preparacion) values(1,"Ensalada","/images/personas1.jpg","Salteado de morrón y cebolla con fideos","*Cortar cebolla y morrón en juliana y freír juntos. - *Hervir una taza de fideos integrales. - *En un plato, agregar una capa de fideos y otra del salteado.")
INSERT INTO recetas (rec_estado,rec_categoria,rec_imagen,rec_nombre,rec_preparacion) values(1,"Pan","/images/personas2.jpg","Pan casero de avena","*Preparar una mezcla de harina integral, 1 huevo, polvo para hornear, 2 cucharadas de avena y agua. - *Realizar una mecla uniforme y vertir sobre un molde. - *Añadir mix de semillas y hornear por 1 hora. - *Dejar reposar.")
INSERT INTO recetas (rec_estado,rec_categoria,rec_imagen,rec_nombre,rec_preparacion) values(1,"Pescado","/images/personas3.jpeg","Atún con arroz","*Hervir una taza de arroz. - *Incorporar 1/4 de lata de atún al natural. - *Añadir 2 tomates cortados en rodajas.")
INSERT INTO recetas (rec_estado,rec_categoria,rec_imagen,rec_nombre,rec_preparacion) values(1,"Pescado","/images/personas1.jpg","Corvina con verduras","*Precalentar el horno a 180 grados y preparar una bandeja o fuente grande con una porción de papel de aluminio. - *Pelar ligeramente las zanahorias y cortar en bastones. - *Añadir la zanahoria, limón y aceite. - *Hornear por 5-8 minutos.")
INSERT INTO recetas (rec_estado,rec_categoria,rec_imagen,rec_nombre,rec_preparacion) values(1,"Pollo","/images/personas2.jpg","Tortilla de pollo","*Cortar la pechuga en trocitos, la cebolla y el morrón también. - *En una sartén pochar la cebolla, añadir el morrón y a continuación, cuando esté blanco, el pollo. - *Batir los huevos con sal y añadir a la sartén con el sofrito. Cuajar la tortilla.")

INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(2,1)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(9,1)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(2,2)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(8,2)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(9,2)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(4,3)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(5,3)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(6,3)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(7,3)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(12,3)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(17,3)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(5,4)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(9,4)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(18,4)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(10,5)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(11,5)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(12,5)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(13,5)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(3,6)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(4,6)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(6,6)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(3,7)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(8,7)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(16,7)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(17,7)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(1,8)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(10,8)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(16,8)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(17,8)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(18,8)

INSERT INTO testimonios (test_fecha, test_comentario, usu_id, test_estado) values ('2023-07-09', '¡Increíble servicio! Me encantó la atención al cliente y la calidad de los productos. Definitivamente los recomendaré a mis amigos y familiares. ¡Gracias!', 1, true);
INSERT INTO testimonios (test_fecha, test_comentario, usu_id, test_estado) values ('2023-07-09', 'Hace tiempo que buscaba una empresa confiable para satisfacer mis necesidades. Encontré exactamente lo que necesitaba con ustedes. ¡Son los mejores!', 2, true);
INSERT INTO testimonios (test_fecha, test_comentario, usu_id, test_estado) values ('2023-07-09', 'No puedo expresar lo feliz que estoy con mi compra. El proceso fue fácil, el envío rápido y el producto superó mis expectativas. ¡No podría pedir más!', 5, true);
INSERT INTO testimonios (test_fecha, test_comentario, usu_id, test_estado) values ('2023-07-09', 'Recomiendo mucho esta pagina. Llevo 8kg bajados desde que comence a usar sus recetas!! 10 de 10 !! ', 3, true);