INSERT INTO usuario (codigo,nombre,apellido,estatura,fecha_nacimiento,tipo_usuario) values("12345","Elias","Solis",165,"1993-10-28",1)
INSERT INTO usuario (codigo,nombre,apellido,estatura,fecha_nacimiento,tipo_usuario) values("5414","Laura","Flores",158,"1995-01-08",0)

INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Pollo")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Carne")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Pescado")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Arroz")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Fideo integral")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Tomate")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Lechuga")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Zanahoria")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Cebolla")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Huevo")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Harina integral")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Semillas varias")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Avena")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Nueces")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Granola")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Aceite")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Limón")
INSERT INTO ingredientes (ing_estado,ing_nombre) values(1,"Morrón")

INSERT INTO recetas (rec_estado,rec_categoria,rec_imagen,rec_nombre,rec_preparacion) values(1,"Carne","../images/personas1","Bistec encebollado","*Cortar cebollas en juliana. - *Calentar aceite de oliva en sartén y freír la cebolla. - *Luego de la cebolla, cocinar el bistec y sasonar a gusto.")
INSERT INTO recetas (rec_estado,rec_categoria,rec_imagen,rec_nombre,rec_preparacion) values(1,"Carne","../images/personas2","Ternera con verduras","*Cortar ternera, zanahoria y cebolla en tiras largas. - *Preparar un wok con una pizca de aceite a fuego lento. - *Cocinar hasta que la cebolla adquiera una tonalidad translúcida.")
INSERT INTO recetas (rec_estado,rec_categoria,rec_imagen,rec_nombre,rec_preparacion) values(1,"Ensalada","../images/personas3","Ensalada mixta con arroz","*Cortar tomate y zanahoria en cubos, agregar unas hojas de lechuga. - *Hervir una taza de arroz. - *En un plato, agregar una capa de arroz y otra de verduras. - *Agregar mix de semillas.")
INSERT INTO recetas (rec_estado,rec_categoria,rec_imagen,rec_nombre,rec_preparacion) values(1,"Ensalada","../images/personas1","Salteado de morrón y cebolla con fideos","*Cortar cebolla y morrón en juliana y freír juntos. - *Hervir una taza de fideos integrales. - *En un plato, agregar una capa de fideos y otra del salteado.")
INSERT INTO recetas (rec_estado,rec_categoria,rec_imagen,rec_nombre,rec_preparacion) values(1,"Pan","../images/personas2","Pan casero de avena","*Preparar una mezcla de harina integral, 1 huevo, polvo para hornear, 2 cucharadas de avena y agua. - *Realizar una mecla uniforme y vertir sobre un molde. - *Añadir mix de semillas y hornear por 1 hora. - *Dejar reposar.")
INSERT INTO recetas (rec_estado,rec_categoria,rec_imagen,rec_nombre,rec_preparacion) values(1,"Pescado","../images/personas2","Atún con arroz","*Hervir una taza de arroz. - *Incorporar 1/4 de lata de atún al natural. - *Añadir 2 tomates cortados en rodajas.")
INSERT INTO recetas (rec_estado,rec_categoria,rec_imagen,rec_nombre,rec_preparacion) values(1,"Pescado","../images/personas3","Corvina con verduras","*Precalentar el horno a 180ºC y preparar una bandeja o fuente grande. Seleccionar además una gran porción de papel de aluminio, suficiente para envolver por completo el pescado y poder retorcerlos bordes. - *Pelar ligeramente las zanahorias y cortar en bastones. - *Añadir la zanahoria dentro del papel aluminio, agregar limón y aceite. - *Hornear por 5-8 minutos.")
INSERT INTO recetas (rec_estado,rec_categoria,rec_imagen,rec_nombre,rec_preparacion) values(1,"Pollo","../images/personas1","Tortilla de pollo","*Cortar la pechuga de pollo en trocitos, la cebolla y el morrón también. - *En una sartén pochar la cebolla, añadir el morrón y a continuación, cuando esté blanco, el pollo. - *Batir los huevos con sal y añadir a la sartén con el sofrito. Cuajar la tortilla.")

INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(2,1)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(9,1)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(2,2)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(8,2)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(9,2)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(4,3)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(5,3)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(6,3)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(7,3)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(12,3)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(17,3)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(5,4)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(9,4)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(18,4)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(10,5)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(11,5)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(12,5)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(13,5)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(3,6)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(4,6)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(6,6)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(3,7)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(8,7)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(16,7)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(17,7)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(1,8)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(10,8)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(16,8)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(17,8)
INSERT INTO recetas_lista_ingredientes(lista_ingredientes_ing_id,receta_rec_id) values(18,8)


INSERT INTO testimonios (codigo, descripcion, usu_id) values("1", "Muy rico", "1")
